name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name:  Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: Build & Push to DockerHub
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: oliviermj/php8.0-fpm-dev-symfony-xdebug:latest
      continue-on-error: false
      
    - name: Discord Message Notify for succes
      if: steps.build.conclusion == success()
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        message: ${{ github.repository }} has been constructed and published on Dockerhub

    - name: Discord Message Notify for failed
      if: steps.build.conclusion == failure()
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#d42405"
        username: "GitHub Bot"
        message: Build failed
      


