name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name:  Checkout
      uses: actions/checkout@v2
   
    - name: Build & Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: oliviermj/php8.0-fpm-dev-symfony-xdebug
        tag_with_ref: true
        tags: oliviermj/php8.0-fpm-dev-symfony-xdebug:latest

